apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world  # unique name for hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/leon-new/SamplegitOpsApp.git'
    path: argo-cd/hello-world
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

